Zen extension update script (#1519)
* add script to address zen extensions

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* tweaks

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* add logic for interpreting and applying parameter cm for zen custom route

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* add custom route field, specify namespace

* add zen extensions cleanup logic

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* remove code referencing custom route or parameter configmap

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* add in changes from other prs

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* add zenextensions to permissions

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* move check to after messages

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* edit deployment check

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* update parameters for extension script

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* debug

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* remove extension namespace

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* grab the correct value for extension name

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* exclude OOTB extensions

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* remove customization cm

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* update deployment wait line

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

* quick fix for cert manager

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

---------

Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

diff --git a/velero/schedule/zen5-br-scripts-cm.yaml b/velero/schedule/zen5-br-scripts-cm.yaml
--- a/velero/schedule/zen5-br-scripts-cm.yaml
+++ b/velero/schedule/zen5-br-scripts-cm.yaml
@@ -130,6 +130,7 @@ data:
     #[2.2.1] Set Zen namespace
     ZEN_NAMESPACE=$1 #should probably defualt this to zen with an optional parameter
     ZENSERVICE_NAME=$2
+
     BACKUP_DIR=/zen5/zen-backup
 
     function main {
@@ -137,8 +138,17 @@ data:
         info "Enabling Zen operator maintenance mode and scale down deployments"
         #[2.2.2] Enable Zen operator maintenance mode and scale down deployments
         oc patch zenservice ${ZENSERVICE_NAME} --namespace ${ZEN_NAMESPACE} --type=merge --patch '{"spec": {"ignoreForMaintenance": true}}'
+        
         #suspend backup cronjob
         oc patch cj zen-metastore-backup-cron-job --namespace ${ZEN_NAMESPACE} --type=merge --patch '{"spec": {"suspend": true}}'
+        
+        #Getting the replica count before scaling down the required pods
+        IBM_NGINX_RC=$(oc get deploy ibm-nginx -n ${ZEN_NAMESPACE} -o=jsonpath='{.spec.replicas}')
+        ZEN_CORE_RC=$(oc get deploy zen-core -n ${ZEN_NAMESPACE} -o=jsonpath='{.spec.replicas}')
+        USERMGMT_RC=$(oc get deploy usermgmt -n ${ZEN_NAMESPACE} -o=jsonpath='{.spec.replicas}')
+        ZEN_CORE_API_RC=$(oc get deploy zen-core-api -n ${ZEN_NAMESPACE} -o=jsonpath='{.spec.replicas}')
+        ZEN_WATCHER_RC=$(oc get deploy zen-watcher -n ${ZEN_NAMESPACE} -o=jsonpath='{.spec.replicas}')
+
         oc get deploy ibm-nginx zen-core usermgmt zen-watcher  zen-watchdog zen-core-api -n ${ZEN_NAMESPACE}
         
         #Getting the replica count before scaling down the required pods
@@ -170,6 +180,19 @@ data:
             deployments_clear=$(oc get deploy -n $ZEN_NAMESPACE | grep "ibm-nginx\|zen-core\|usermgmt\|zen-watcher\|zen-core-api\|zen-watchdog" | grep -v "ibm-nginx-tester" | awk '{print $3}' | grep -v 0 || echo clear)
         done
 
+        #waiting for deployments to be cleaned up after scaling down
+        deployments_clear=$(oc get deploy -n $ZEN_NAMESPACE | grep "ibm-nginx\|zen-core\|usermgmt\|zen-watcher\|zen-core-api\|zen-watchdog" | grep -v "ibm-nginx-tester" | awk '{print $4}' | grep -v 0 || echo clear)
+        while [[ $deployments_clear != "clear" ]];
+        do
+            sleep 10
+            if [[ $deployments_clear != "clear" ]]; then
+                info "Waiting on deployments ibm-nginx zen-core usermgmt zen-watcher zen-core-api to clean up..."
+            else
+                info "Deployments ibm-nginx zen-core usermgmt zen-watcher zen-core-api successfully scaled down. Moving on..."
+            fi
+            deployments_clear=$(oc get deploy -n $ZEN_NAMESPACE | grep "ibm-nginx\|zen-core\|usermgmt\|zen-watcher\|zen-core-api\|zen-watchdog" | grep -v "ibm-nginx-tester" | awk '{print $4}' | grep -v 0 || echo clear)
+        done
+        
         info "Reset patform metadata and configuration data"
         #[2.2.3] Reset platform metadata and configuration data
         #[2.2.3.1] Reset database
@@ -213,6 +236,9 @@ data:
         oc patch secret -n $ZEN_NAMESPACE zen-secrets-aes-key --patch="{\"data\": { \"aes_key\": \"$(base64 -w0 $BACKUP_DIR/secrets/aes_key)\" }}"
         oc patch secret -n $ZEN_NAMESPACE admin-user-details --patch="{\"data\": { \"initial_admin_password\": \"$(base64 -w0 $BACKUP_DIR/secrets/initial_admin_password)\" }}"
 
+        #Possible site for running extension script
+        ./zen5/customize-zen-extensions.sh $ZEN_NAMESPACE
+        
         #[2.2.5] Scale up deployments and Disable Zen operator maintenance mode
         #[2.2.5.1] Scale up the deployments
         info "Scale up deployments."
@@ -236,6 +262,7 @@ data:
             info "zen-watcher deployment not scaled up before rerunning, setting replica value to 1"
             ZEN_WATCHER_RC=1
         fi
+        
         oc scale deploy zen-watcher --replicas=$ZEN_WATCHER_RC -n $ZEN_NAMESPACE
         oc scale deploy usermgmt --replicas=$USERMGMT_RC -n $ZEN_NAMESPACE
         oc scale deploy zen-core-api --replicas=$ZEN_CORE_API_RC -n $ZEN_NAMESPACE
@@ -296,4 +323,91 @@ data:
         msg "[INFO] ${1}"
     }
 
+    main $*
+  customize-zen-extensions.sh: |
+    #!/usr/bin/env bash
+    #
+    # Copyright 2023 IBM Corporation
+    #
+    # Licensed under the Apache License, Version 2.0 (the "License");
+    # you may not use this file except in compliance with the License.
+    # You may obtain a copy of the License at
+    #
+    # http://www.apache.org/licenses/LICENSE-2.0
+    #
+    # Unless required by applicable law or agreed to in writing, software
+    # distributed under the License is distributed on an "AS IS" BASIS,
+    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+    # See the License for the specific language governing permissions and
+    # limitations under the License.
+    #
+    set -o errexit
+
+    ZEN_NAMESPACE=$1
+
+    function main(){
+
+        title "Begin zen extension cleanup process."
+        # Get broker secret value from secret zen-service-broker-secret
+        broker_secret=$(oc get secret zen-service-broker-secret -o yaml -n $ZEN_NAMESPACE | yq .data.token | base64 -d || echo "fail") 
+        if [[ $broker_secret == "fail" ]]; then
+            error "Failed to grab broker secret zen-service-broker-secret in namespace $ZEN_NAMESPACE"
+        else
+            info "Broker Secret obtained in namespace $ZEN_NAMESPACE"
+        fi
+
+        extensions=$(oc get zenextension -n $ZEN_NAMESPACE -o yaml | grep "extension_name" | grep -v "bedrock-idp-locations\|zen-watchdog-routes" | awk '{print $2}' | tr '\"\n' ' ' | tr ',' " ")
+        extensions=$(echo $extensions | tr " " ",")
+        if [[ -z $extensions ]]; then
+            info "No extensions found in namespace $ZEN_NAMESPACE, exiting."
+        else
+            info "Extensions to cleanup in namespace $ZEN_NAMESPACE: $extensions"
+            # curl -H 'secret: <broker-secret>' -ks https://zen-core-api-svc:4444/v1/extensions?extension_name=bawtest-bas-extension,ibm-bts-zen-frontdoor,icp4adeploy-ban-zen-extension,icp4adeploy-cp4ba-zen-extension,icp4adeploy-graphql-zen-extension,icp4adeploy-cmis-zen-extension,icp4adeploy-cpe-zen-extension,icp4adeploy-rr-bawtest-zen-ext
+            #curl_output=$(curl -H "secret: ${broker_secret}" -ks https://zen-core-api-svc:4444/v1/extensions?extension_name=${extensions})
+
+            # Extract ID of each extension
+            id_list=$(curl -H "secret: ${broker_secret}" -ks https://zen-core-api-svc:4444/v1/extensions?extension_name=${extensions} | yq eval '.data[] | select(.id == "*") | .id' | tr '\n' ' ') #space separated list of ids
+            info "id_list: $id_list bookend"
+            if [[ -z $id_list ]] || [[ $id_list == "" ]]; then
+                error "The list of extensions provdided returned an empty ID list from the database. These extensions may not be present in this database."
+            else
+                info "List of extension IDs populated, continuing with deletion."
+            fi
+
+            # Delete each extension using the ID
+            # curl -H 'secret: <broker-secret>' -ks -X DELETE https://zen-core-api-svc:4444/v1/extensions/{id}
+            for id in $id_list; do
+                info "Deleting extension with ID $id."
+                curl -H "secret: ${broker_secret}" -ks -X DELETE https://zen-core-api-svc:4444/v1/extensions/{$id}
+            done
+
+            success "Zen extension cleanup complete."
+        fi
+    }
+
+    function msg() {
+        printf '%b\n' "$1"
+    }
+
+    function success() {
+        msg "\33[32m[✔] ${1}\33[0m"
+    }
+
+    function warning() {
+        msg "\33[33m[✗] ${1}\33[0m"
+    }
+
+    function error() {
+        msg "\33[31m[✘] ${1}\33[0m"
+        exit 1
+    }
+
+    function title() {
+        msg "\33[34m# ${1}\33[0m"
+    }
+
+    function info() {
+        msg "[INFO] ${1}"
+    }
+    
     main $*
