add logic for interpreting and applying parameter cm for zen custom route
Signed-off-by: Ben Luzarraga <luzarragaben@gmail.com>

diff --git a/velero/schedule/zen5-br-scripts-cm.yaml b/velero/schedule/zen5-br-scripts-cm.yaml
--- a/velero/schedule/zen5-br-scripts-cm.yaml
+++ b/velero/schedule/zen5-br-scripts-cm.yaml
@@ -130,6 +130,29 @@ data:
         info "Enabling Zen operator maintenance mode and scale down deployments"
         #[2.2.2] Enable Zen operator maintenance mode and scale down deployments
         oc patch zenservice ${ZENSERVICE_NAME} --namespace ${ZEN_NAMESPACE} --type=merge --patch '{"spec": {"ignoreForMaintenance": true}}'
+        
+        #check for parameter configmap for custom route changes
+        info "Checking for configmap zen5-customization-configmap in $ZEN_NAMESPACE."
+        cm_exists=$(oc get configmap -n $ZEN_NAMESPACE zen5-customization-configmap --ignore-not-found || echo "fail")
+        if [[ $cm_exists != "fail" ]]; then
+            route=$(oc get configmap -n $ZEN_NAMESPACE zen5-customization-configmap -o=jsonpath='{.data.custom_route}')
+            info "Configmap zen5-customization-configmap found in $ZEN_NAMESPACE. New zen Custom Route: ${route}"
+            instance=`oc get zenservice ${ZENSERVICE_NAME} -n ${ZEN_NAMESPACE} -o yaml --ignore-not-found | yq '
+                with(.; del(.metadata.creationTimestamp) |
+                del(.metadata.managedFields) |
+                del(.metadata.resourceVersion) |
+                del(.metadata.uid) |
+                del(.status) |
+                .spec.zenCustomRoute.route_host = "'${route}'"
+                )
+                ' | sed -e 's/^/    /g'`
+    cat << _EOF | oc apply -f -
+    ${instance}
+    _EOF
+        else
+            info "Configmap zen5-customization-configmap not present in $ZEN_NAMESPACE. Skipping custom route update."
+        fi
+        
         #suspend backup cronjob
         oc patch cj zen-metastore-backup-cron-job --namespace ${ZEN_NAMESPACE} --type=merge --patch '{"spec": {"suspend": true}}'
         oc get deploy ibm-nginx zen-core usermgmt zen-watcher  zen-watchdog zen-core-api -n ${ZEN_NAMESPACE}
